# 💰 Supported funding platforms for this project

github: [MidknightMantra]
patreon: # Add your Patreon username here
open_collective: # Add your Open Collective username here
ko_fi: # Add your Ko-fi username here
tidelift: # Example: npm/babel
community_bridge: # Example: cloud-foundry
liberapay: [MidknightMantra]
issuehunt: # Add your IssueHunt username here
otechie: # Add your Otechie username here
custom:
  - 'https://github.com/MidknightMantra/Miara'
