/**
 * 🌌 Miara Command: QR — Celestial Encoder
 * -----------------------------------------
 * Transmutes any text or link into a glowing digital sigil (QR Code).
 * by MidKnightMantra 🌸 — “Every code carries a whisper of its creator.”
 */

import QRCode from "qrcode";
import { config } from "../config.js";

export default {
  name: "qr",
  aliases: ["qrcode", "sigil", "encode"],
  description: "Transform text or links into luminous QR sigils ✨",
  category: "tools",
  usage: ".qr <text_or_url>",

  async execute(conn, m, args) {
    const { from } = m;
    const qrData = args.join(" ").trim();

    // 🧩 Input validation
    if (!qrData) {
      await conn.sendMessage(from, {
        text: "🌙 Please share text or a link to encode.\nExample:\n.qr https://miara.ai\n.qr Miara awakens 🌸",
      });
      return;
    }

    // 💫 Determine the kind of content
    const isUrl = /^https?:\/\//i.test(qrData);
    const typeEmoji = isUrl ? "🌐" : qrData.length > 30 ? "📜" : "💠";
    const title = isUrl ? "Celestial Link Portal" : "Encoded Sigil";

    try {
      console.log(`✨ Generating QR code for: ${qrData}`);

      // 🎨 Generate QR code (violet aesthetic)
      const qrBuffer = await QRCode.toBuffer(qrData, {
        width: 400,
        margin: 2,
        color: {
          dark: "#4B0082", // Indigo glow
          light: "#FAF5FF", // Soft lavender background
        },
      });

      // 🌸 Caption design
      const caption = `
${typeEmoji} *${title}*
──────────────────────
📦 *Content:* \`\`\`${qrData}\`\`\`
🪷 *Generated by:* ${config.BOT_NAME || "Miara 🌸"}
🌠 *Timestamp:* ${new Date().toLocaleString()}
      `.trim();

      // ✉️ Send the QR code image
      await conn.sendMessage(from, {
        image: qrBuffer,
        caption,
      });

      // React (if message key exists)
      if (m?.key) {
        await conn.sendMessage(from, { react: { text: "💫", key: m.key } });
      }

      console.log(`✅ QR code sent successfully to ${from}`);
    } catch (err) {
      console.error("❌ QR generation error:", err);
      const errorText = `
⚠️ *QR Transmutation Failed*
──────────────────────
🪞 Reason: ${err.message || "Unknown error"}
💭 Hint: Try simpler text or shorter URLs.
      `.trim();

      await conn.sendMessage(from, { text: errorText });

      if (m?.key) {
        await conn.sendMessage(from, { react: { text: "💔", key: m.key } });
      }
    }
  },
};
