/**
 * 🌌 Miara Command: QR — Celestial Encoder (Baileys 7-Ready)
 * -----------------------------------------------------------
 * Transmutes any text or link into a glowing digital sigil (QR Code).
 * by MidKnightMantra 🌸 — “Every code carries a whisper of its creator.”
 */

import QRCode from "qrcode";
import { config } from "../config.js";
import { safeQuoted, safeReact } from "../utils/helpers.js";

export default {
  name: "qr",
  aliases: ["qrcode", "sigil", "encode"],
  description: "Transform text or links into luminous QR sigils ✨",
  category: "tools",
  usage: ".qr <text_or_url>",

  async execute(conn, m, args) {
    try {
      const chat = m.key.remoteJid;
      const qrData = args.join(" ").trim();

      // 🧩 Validate input
      if (!qrData) {
        await conn.sendMessage(
          chat,
          {
            text:
              "🌙 Please share text or a link to encode.\n\n" +
              "Example:\n.qr https://miara.ai\n.qr Miara awakens 🌸"
          },
          safeQuoted(m)
        );
        return;
      }

      // 🌸 Identify content
      const isUrl = /^https?:\/\//i.test(qrData);
      const typeEmoji = isUrl ? "🌐" : qrData.length > 30 ? "📜" : "💠";
      const title = isUrl ? "Celestial Link Portal" : "Encoded Sigil";

      await safeReact(conn, m, "✨");
      console.log(`✨ Generating QR code for: ${qrData}`);

      // 🎨 Generate QR buffer
      const qrBuffer = await QRCode.toBuffer(qrData, {
        width: 400,
        margin: 2,
        color: {
          dark: "#4B0082", // Indigo glow
          light: "#FAF5FF" // Soft lavender background
        }
      });

      // 🌸 Caption
      const caption = `
${typeEmoji} *${title}*
──────────────────────
📦 *Content:* \`\`\`${qrData}\`\`\`
🪷 *Generated by:* ${config.BOT_NAME || "Miara 🌸"}
🌠 *Timestamp:* ${new Date().toLocaleString()}
      `.trim();

      // ✉️ Send QR image safely
      await conn.sendMessage(
        chat,
        {
          image: qrBuffer,
          caption
        },
        safeQuoted(m)
      );

      await safeReact(conn, m, "💫");
      console.log(`✅ QR code sent successfully to ${chat}`);
    } catch (err) {
      console.error("❌ QR generation error:", err);
      const errorText = `
⚠️ *QR Transmutation Failed*
──────────────────────
🪞 Reason: ${err.message || "Unknown error"}
💭 Hint: Try simpler text or shorter URLs.
      `.trim();

      const chat = m?.key?.remoteJid;
      if (chat) {
        await conn.sendMessage(chat, { text: errorText }, safeQuoted(m));
        await safeReact(conn, m, "💔");
      }
    }
  }
};
